### ISSUE TITLE
SystemController - Inotify on settings file (PROTOTYPE THREAD) 

### ISSUE THREAD

**Issue by Malthep1** [Malthep1/SemesterProjekt3#14]
Nice idea to implement the listenerThread as a nested class, however make sure the naming convention is still PascalCase to avoid confusion.

Otherwise LGTM - Review OK

Side notes:
We should remove the debug comments before merging.

I can see you haven't uploaded the OSAPI on git yet. This should also be done before merging.

When the  OSAPI is uploaded, a note of it being used should be made in README.md, along with "how to build and run SystemManager section"

**Comment by MarcinSzymanek** [comment]
Thread lavet af SystemManager::listenSettingsUpdate()

**Comment by MarcinSzymanek** [comment]
When testing, change PATHNAME in SystemManager.cpp to the correct path to the file on your system.
